name: Deploy Server
on:
  push:
    branches:
      - release
      - dev_2
jobs:
  deploy:
    strategy:
      matrix:
        branch_name: [dev_2, release]
    runs-on: [ubuntu-latest]
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: deploy server from branch ${{ matrix.branch_name}}
        uses: appleboy/ssh-action@master
        if: steps.extract_branch.outputs.branch == matrix.branch_name
        env:
          PROJECT_PATH: /home/server/www/fe_linkaran
          PROJECT_PATH_ADMIN: /home/server/www/admin_linkaran
          DEPLOY_BRANCH: ${{ matrix.branch_name }}
        with:
          username: server
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          host: ${{ secrets.SSH_SERVER}}
          envs: |
            PROJECT_PATH
            PROJECT_PATH_ADMIN
            DEPLOY_BRANCH
          script: |
            echo "deploy from branch $DEPLOY_BRANCH"
            case "$DEPLOY_BRANCH" in 
              "dev_2") cd $PROJECT_PATH ;;
              "release") cd $PROJECT_PATH_ADMIN ;;
            esac
            git pull origin $DEPLOY_BRANCH
            yarn 
            yarn build
