name: Deploy Server
on:
  push:
    branches:
      - master
      - dev_2
jobs:
  deploy:
    # needs: [build, release]
    runs-on: [ubuntu-latest]
    steps:
      # - name: remote server
      #   uses: appleboy/ssh-action@master
      #   env:
      #     PROJECT_PATH: /root/www/backend_linkaran
      #   with:
      #     username: root
      #     key: ${{ secrets.SSH_PRIVATE_KEY}}
      #     host: ${{ secrets.SSH_SERVER}}
      #     envs: PROJECT_PATH
      #     script: |
      #       cd $PROJECT_PATH
      #       cp -rf ~/artifacts/linkaran .
      #       ~/.nvm/versions/node/v12.13.0/bin/npm install
      #       NODE_ENV=production yarn typeorm:sync
      #       pm2 start ecosystem.config.js --env=production
